export const VALIDATE = {
  PASSWORD_MAX_LENGTH: 50,
  PASSWORD_MIN_LENGTH: 8,
  LOGINID_MIN_LENGTH: 5,
  LOGINID_MAX_LENGTH: 50,
  NAME_MAX_LENGTH: 128,
  EMAIL_MAX_LENGTH: 256,
  PHONE_MAX_LENGTH: 13,
};
export enum FIELD_TYPE {
  TEXT_INPUT,
  INLINE_SELECT,
  CHECKBOX,
  DATE_PICKER,
  DIV,
  COMBO_BOX,
}
export enum USER_ROLE {
  ADMIN = 1,
  PC,
  FW,
  SUPPLIER,
}

export enum SORT_STATUS {
  ASC = 'asc',
  DESC = 'desc',
}

export const ROLES_DIV: {
  value: USER_ROLE;
  label: string;
}[] = [
    { value: USER_ROLE.ADMIN, label: '管理者' },
    {
      value: USER_ROLE.PC,
      label: 'PC工場担当者',
    },
    {
      value: USER_ROLE.FW,
      label: 'FW購買担当者',
    },
    {
      value: USER_ROLE.SUPPLIER,
      label: 'サプライヤー',
    },
  ];

export enum ORDER_ACTION_DIV {
  ORDER_CONFIRMATION = 1,
  APPROVAL,
  REJECTION,
  DELIVERY_DATE_RESPONSE,
  DELIVERY_DATE_CHANGE,
  DELIVERY_DATE_CHANGE_APPROVAL,
  DELIVERY_DATE_CHANGE_REJECTION,
  CANCELLATION,
  CANCELLATION_APPROVAL_BY_FW,
  CANCELLATION_APPROVAL_BY_SUPPLIER,
  CANCELLATION_REJECTION_BY_FW,
  CANCELLATION_REJECTION_BY_SUPPLIER,
  ORDER_CHANGE,
  ORDER_CHANGE_APPROVAL_BY_FW,
  ORDER_CHANGE_APPROVAL_BY_SUPPLIER,
  ORDER_CHANGE_REJECTION_BY_FW,
  ORDER_CHANGE_REJECTION_BY_SUPPLIER,
  COMPLETE_DELIVERY,
}

export enum ORDER_STATUS_DIV {
  ORDER_NOT_CONFIRM = 1,
  DELIVERY_DATE_UNDETERMINED,
  DELIVERY_DATE_CONFIRMED,
  DELIVERY_DATE_CHANGE_REQUEST,
  CANCELLATION_REQUEST,
  CANCELLATION_APPROVED,
  CANCELED,
  CHANGE_REQUEST,
  CHANGE_DELIVERY_DATE_UNCONFIRMED,
  DELIVERED,
}
export enum ITEMGROUP {
  ITEM1 = 1,
  ITEM2,
  ITEM3,
  ITEM4,
  ITEM5,
  ITEM6,
}

export enum ITEM_DISPLAY_DIV {
  TABULAR = 1,
  PULLDOWN,
}

export enum SAVE_DRAFT {
  ADD_DESTINATION = 1,
  SAVE_TEMP,
}
